/**
 * Supplemental N4 grammar imported from the Minna markdown review source.
 * Generated by scripts/import-n4-minna-md.mjs.
 */

import type { GrammarItem } from '$lib/types';

export const SUPPLEMENTAL_MINNA_N4_GRAMMAR: GrammarItem[] = [
  {
    pattern: "Vていただけませんか",
    vietnamese: "Anh/chị làm ơn… giúp tôi được không?",
    english: "V-te itadakemasen ka",
    type: "additional",
    explanation: "Nhờ vả lịch sự với người trên, khách hàng, giáo viên.\nRomaji: V-te itadakemasen ka",
    examples: [
      {
        japanese: "いい先生を紹介していただけませんか。",
        vietnamese: "Anh/chị có thể giới thiệu giúp tôi một giáo viên tốt được không?",
        english: "Ii sensei o shoukai shite itadakemasen ka."
      }
    ],
    category: "1. Nhóm nhờ vả, xin ý kiến và xin phép"
  },
  {
    pattern: "Từ để hỏi + Vたらいいですか",
    vietnamese: "Nên làm gì / ở đâu / khi nào / như thế nào thì được?",
    english: "Từ để hỏi + V-tara ii desu ka",
    type: "additional",
    explanation: "Hỏi lời khuyên khi chưa biết nên làm gì.\nRomaji: Từ để hỏi + V-tara ii desu ka",
    examples: [
      {
        japanese: "バレンタインデーに何をあげたらいいですか。",
        vietnamese: "Valentine thì nên tặng gì?",
        english: "Barentain dē ni nani o agetara ii desu ka."
      }
    ],
    category: "1. Nhóm nhờ vả, xin ý kiến và xin phép"
  },
  {
    pattern: "どうすればいいですか",
    vietnamese: "Làm thế nào thì được?",
    english: "Dou sureba ii desu ka",
    type: "additional",
    explanation: "Hỏi cách xử lý, phương pháp.\nRomaji: Dou sureba ii desu ka",
    examples: [
      {
        japanese: "電話番号がわからないんですが、どうすればいいですか。",
        vietnamese: "Tôi không biết số điện thoại, phải làm thế nào?",
        english: "Denwa bangou ga wakaranai n desu ga, dou sureba ii desu ka."
      }
    ],
    category: "1. Nhóm nhờ vả, xin ý kiến và xin phép"
  },
  {
    pattern: "と伝えていただけませんか",
    vietnamese: "Anh/chị làm ơn truyền đạt lại rằng… được không?",
    english: "To tsutaete itadakemasen ka",
    type: "additional",
    explanation: "Nhờ ai đó chuyển lời nhắn.\nRomaji: To tsutaete itadakemasen ka",
    examples: [
      {
        japanese: "ワンさんに「あとで電話をください」と伝えていただけませんか。",
        vietnamese: "Anh/chị nhắn với anh Wan là ‘hãy gọi điện lại sau’ được không?",
        english: "Wan-san ni ‘ato de denwa o kudasai’ to tsutaete itadakemasen ka."
      }
    ],
    category: "1. Nhóm nhờ vả, xin ý kiến và xin phép"
  },
  {
    pattern: "Vさせていただけませんか",
    vietnamese: "Xin cho tôi được làm…",
    english: "V-sasete itadakemasen ka",
    type: "additional",
    explanation: "Xin phép rất lịch sự để người nói làm việc gì đó.\nRomaji: V-sasete itadakemasen ka",
    examples: [
      {
        japanese: "明日用事がありますから、一日休ませていただけませんか。",
        vietnamese: "Vì ngày mai tôi có việc bận, anh/chị cho tôi nghỉ một ngày được không?",
        english: "Ashita youji ga arimasu kara, ichinichi yasumasete itadakemasen ka."
      }
    ],
    category: "1. Nhóm nhờ vả, xin ý kiến và xin phép"
  },
  {
    pattern: "Vさせていただきます",
    vietnamese: "Tôi xin phép được làm…",
    english: "V-sasete itadakimasu",
    type: "additional",
    explanation: "Thông báo hành động của mình một cách khiêm nhường.\nRomaji: V-sasete itadakimasu",
    examples: [
      {
        japanese: "先に帰らせていただきます。",
        vietnamese: "Tôi xin phép về trước.",
        english: "Saki ni kaerasete itadakimasu."
      }
    ],
    category: "1. Nhóm nhờ vả, xin ý kiến và xin phép"
  },
  {
    pattern: "Vる / Vた / Vない + んです",
    vietnamese: "Là…, vì…, thật ra là…",
    english: "V-ru / V-ta / V-nai + n desu",
    type: "additional",
    explanation: "Dùng để giải thích lý do, hỏi nguyên nhân, làm mềm câu. Không dùng với Vて.\nRomaji: V-ru / V-ta / V-nai + n desu",
    examples: [
      {
        japanese: "どうして遅れたんですか。",
        vietnamese: "Tại sao bạn đến muộn vậy?",
        english: "Doushite okureta n desu ka."
      }
    ],
    category: "2. Nhóm giải thích lý do và làm mềm câu"
  },
  {
    pattern: "Aい + んです",
    vietnamese: "Là vì tính chất…",
    english: "A-i + n desu",
    type: "additional",
    explanation: "Dùng với tính từ đuôi i để giải thích tình trạng.\nRomaji: A-i + n desu",
    examples: [
      {
        japanese: "今日は忙しいんです。",
        vietnamese: "Hôm nay tôi bận.",
        english: "Kyou wa isogashii n desu."
      }
    ],
    category: "2. Nhóm giải thích lý do và làm mềm câu"
  },
  {
    pattern: "Aな / N + なんです",
    vietnamese: "Là vì…",
    english: "A-na / N + nan desu",
    type: "additional",
    explanation: "Với tính từ na và danh từ phải dùng なんです.\nRomaji: A-na / N + nan desu",
    examples: [
      {
        japanese: "調子が悪いんです。",
        vietnamese: "Tôi thấy không khỏe.",
        english: "Choushi ga warui n desu."
      }
    ],
    category: "2. Nhóm giải thích lý do và làm mềm câu"
  },
  {
    pattern: "まだわからないんですが、Vていただけませんか",
    vietnamese: "Tôi vẫn chưa hiểu, anh/chị có thể… không?",
    english: "Mada wakaranai n desu ga, V-te itadakemasen ka",
    type: "additional",
    explanation: "Dùng んですが để mở đầu nhờ vả mềm hơn.\nRomaji: Mada wakaranai n desu ga, V-te itadakemasen ka",
    examples: [
      {
        japanese: "まだわからないんですが、もう一度教えていただけませんか。",
        vietnamese: "Tôi vẫn chưa hiểu, anh/chị chỉ lại một lần nữa được không?",
        english: "Mada wakaranai n desu ga, mou ichido oshiete itadakemasen ka."
      }
    ],
    category: "2. Nhóm giải thích lý do và làm mềm câu"
  },
  {
    pattern: "Nが + động từ thể khả năng",
    vietnamese: "Có thể làm N",
    english: "N ga + kanou-kei",
    type: "additional",
    explanation: "Khi dùng thể khả năng, đối tượng thường đi với が.\nRomaji: N ga + kanou-kei",
    examples: [
      {
        japanese: "漢字が書けます。",
        vietnamese: "Tôi có thể viết Kanji.",
        english: "Kanji ga kakemasu."
      }
    ],
    category: "3. Nhóm khả năng, giới hạn và hoàn thành"
  },
  {
    pattern: "N1は〜が、N2は〜",
    vietnamese: "N1 thì có thể…, nhưng N2 thì…",
    english: "N1 wa ... ga, N2 wa ...",
    type: "additional",
    explanation: "So sánh khả năng giữa hai đối tượng.\nRomaji: N1 wa ... ga, N2 wa ...",
    examples: [
      {
        japanese: "日本語は話せますが、英語は話せません。",
        vietnamese: "Tôi có thể nói tiếng Nhật nhưng không thể nói tiếng Anh.",
        english: "Nihongo wa hanasemasu ga, eigo wa hanasemasen."
      }
    ],
    category: "3. Nhóm khả năng, giới hạn và hoàn thành"
  },
  {
    pattern: "Nができます",
    vietnamese: "Biết làm / có thể làm N",
    english: "N ga dekimasu",
    type: "additional",
    explanation: "Dùng với danh từ chỉ hoạt động.\nRomaji: N ga dekimasu",
    examples: [
      {
        japanese: "テニスができます。",
        vietnamese: "Tôi biết chơi tennis.",
        english: "Tenisu ga dekimasu."
      }
    ],
    category: "3. Nhóm khả năng, giới hạn và hoàn thành"
  },
  {
    pattern: "Vることができます",
    vietnamese: "Có thể làm việc gì",
    english: "V-ru koto ga dekimasu",
    type: "additional",
    explanation: "Biến động từ thành danh từ hóa bằng こと.\nRomaji: V-ru koto ga dekimasu",
    examples: [
      {
        japanese: "日本語を話すことができます。",
        vietnamese: "Tôi có thể nói tiếng Nhật.",
        english: "Nihongo o hanasu koto ga dekimasu."
      }
    ],
    category: "3. Nhóm khả năng, giới hạn và hoàn thành"
  },
  {
    pattern: "NしかVません = NだけVます",
    vietnamese: "Chỉ…",
    english: "N shika V-masen = N dake V-masu",
    type: "additional",
    explanation: "しか luôn đi với phủ định nhưng nghĩa là ‘chỉ’.\nRomaji: N shika V-masen = N dake V-masu",
    examples: [
      {
        japanese: "私はベトナム語しか話せません。",
        vietnamese: "Tôi chỉ nói được tiếng Việt.",
        english: "Watashi wa betonamugo shika hanasemasen."
      }
    ],
    category: "3. Nhóm khả năng, giới hạn và hoàn thành"
  },
  {
    pattern: "できます",
    vietnamese: "Xong, hoàn thành",
    english: "Dekimasu",
    type: "additional",
    explanation: "Ngoài nghĩa ‘có thể’, できます còn chỉ việc đã hoàn thành.\nRomaji: Dekimasu",
    examples: [
      {
        japanese: "レポートはいつできますか。明日できます。",
        vietnamese: "Báo cáo bao giờ xong? Ngày mai xong.",
        english: "Repōto wa itsu dekimasu ka. Ashita dekimasu."
      }
    ],
    category: "3. Nhóm khả năng, giới hạn và hoàn thành"
  },
  {
    pattern: "Vます bỏ ます + ながら、V2",
    vietnamese: "Vừa… vừa…",
    english: "V-masu stem + nagara, V2",
    type: "additional",
    explanation: "Hai hành động xảy ra cùng lúc; hành động chính thường ở vế sau.\nRomaji: V-masu stem + nagara, V2",
    examples: [
      {
        japanese: "テレビを見ながら、ご飯を食べます。",
        vietnamese: "Tôi vừa xem TV vừa ăn cơm.",
        english: "Terebi o minagara, gohan o tabemasu."
      }
    ],
    category: "4. Nhóm vừa làm vừa làm, nối hành động và liệt kê"
  },
  {
    pattern: "Vながら、Vる人が好き / 嫌いです",
    vietnamese: "Thích / ghét người vừa làm việc này vừa làm việc kia",
    english: "V-nagara, V-ru hito ga suki / kirai desu",
    type: "additional",
    explanation: "Dùng để nhận xét thói quen của người khác.\nRomaji: V-nagara, V-ru hito ga suki / kirai desu",
    examples: [
      {
        japanese: "ご飯を食べながら電話を使う人が嫌いです。",
        vietnamese: "Tôi ghét người vừa ăn vừa dùng điện thoại.",
        english: "Gohan o tabenagara denwa o tsukau hito ga kirai desu."
      }
    ],
    category: "4. Nhóm vừa làm vừa làm, nối hành động và liệt kê"
  },
  {
    pattern: "〜し、〜し、それに",
    vietnamese: "Vừa…, vừa…, hơn nữa…",
    english: "... shi, ... shi, sore ni",
    type: "additional",
    explanation: "Liệt kê tính chất cùng chiều.\nRomaji: ... shi, ... shi, sore ni",
    examples: [
      {
        japanese: "先生は面白いし、親切だし、それに経験もあります。",
        vietnamese: "Thầy/cô vừa thú vị, vừa tốt bụng, hơn nữa còn có kinh nghiệm.",
        english: "Sensei wa omoshiroi shi, shinsetsu da shi, sore ni keiken mo arimasu."
      }
    ],
    category: "4. Nhóm vừa làm vừa làm, nối hành động và liệt kê"
  },
  {
    pattern: "〜し、〜し、それで",
    vietnamese: "Vì vừa…, vừa…, nên…",
    english: "... shi, ... shi, sore de",
    type: "additional",
    explanation: "Liệt kê lý do dẫn đến kết quả.\nRomaji: ... shi, ... shi, sore de",
    examples: [
      {
        japanese: "雨も降っているし、荷物も多いし、それでタクシーで帰りました。",
        vietnamese: "Trời mưa, hành lý nhiều, nên tôi đã về bằng taxi.",
        english: "Ame mo futte iru shi, nimotsu mo ooi shi, sore de takushī de kaerimashita."
      }
    ],
    category: "4. Nhóm vừa làm vừa làm, nối hành động và liệt kê"
  },
  {
    pattern: "V1て V2",
    vietnamese: "Làm V2 trong trạng thái có V1 / nối hành động",
    english: "V1-te V2",
    type: "additional",
    explanation: "Vế trước bổ nghĩa cách làm cho vế sau.\nRomaji: V1-te V2",
    examples: [
      {
        japanese: "しょうゆをつけて食べてください。",
        vietnamese: "Hãy chấm xì dầu rồi ăn.",
        english: "Shouyu o tsukete tabete kudasai."
      }
    ],
    category: "4. Nhóm vừa làm vừa làm, nối hành động và liệt kê"
  },
  {
    pattern: "V1ないで V2",
    vietnamese: "Làm V2 mà không làm V1",
    english: "V1-naide V2",
    type: "additional",
    explanation: "Nhấn mạnh hành động không được thực hiện.\nRomaji: V1-naide V2",
    examples: [
      {
        japanese: "しょうゆをつけないで食べてください。",
        vietnamese: "Hãy ăn mà không chấm xì dầu.",
        english: "Shouyu o tsukenaide tabete kudasai."
      }
    ],
    category: "4. Nhóm vừa làm vừa làm, nối hành động và liệt kê"
  },
  {
    pattern: "いつもVています",
    vietnamese: "Luôn / thường làm gì",
    english: "Itsumo V-te imasu",
    type: "additional",
    explanation: "Diễn tả thói quen lặp lại.\nRomaji: Itsumo V-te imasu",
    examples: [
      {
        japanese: "暇なとき、いつもテレビを見ています。",
        vietnamese: "Khi rảnh, tôi thường xem TV.",
        english: "Hima na toki, itsumo terebi o mite imasu."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Vてしまいます",
    vietnamese: "Làm xong / làm nốt",
    english: "V-te shimaimasu",
    type: "additional",
    explanation: "Nhấn mạnh hoàn thành việc gì.\nRomaji: V-te shimaimasu",
    examples: [
      {
        japanese: "今、この漫画を読んでしまいます。",
        vietnamese: "Bây giờ tôi sẽ đọc nốt cuốn truyện tranh này.",
        english: "Ima, kono manga o yonde shimaimasu."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Vてしまいました",
    vietnamese: "Lỡ… mất / đã làm xong hết",
    english: "V-te shimaimashita",
    type: "additional",
    explanation: "Có thể mang sắc thái tiếc nuối hoặc hoàn thành 100%.\nRomaji: V-te shimaimashita",
    examples: [
      {
        japanese: "財布を忘れてしまいました。",
        vietnamese: "Tôi lỡ quên ví mất rồi.",
        english: "Saifu o wasurete shimaimashita."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Vちゃう / Vじゃう = Vてしまう",
    vietnamese: "Dạng nói tắt của Vてしまう",
    english: "V-chau / V-jau = V-te shimau",
    type: "additional",
    explanation: "Dùng trong văn nói thân mật.\nRomaji: V-chau / V-jau = V-te shimau",
    examples: [
      {
        japanese: "財布を忘れちゃった。",
        vietnamese: "Tôi lỡ quên ví mất rồi.",
        english: "Saifu o wasurechatta."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "[Địa điểm]にNがVてあります",
    vietnamese: "Ở đâu đó có N được… sẵn",
    english: "[Place] ni N ga V-te arimasu",
    type: "additional",
    explanation: "Ai đó đã làm hành động trước và kết quả còn hiện tại.\nRomaji: [Place] ni N ga V-te arimasu",
    examples: [
      {
        japanese: "壁に絵が貼ってあります。",
        vietnamese: "Trên tường có tranh được dán sẵn.",
        english: "Kabe ni e ga hatte arimasu."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Nは[Địa điểm]にVてあります",
    vietnamese: "N thì được… ở đâu",
    english: "N wa [place] ni V-te arimasu",
    type: "additional",
    explanation: "Nhấn mạnh chủ ngữ N.\nRomaji: N wa [place] ni V-te arimasu",
    examples: [
      {
        japanese: "カレンダーは壁に貼ってあります。",
        vietnamese: "Lịch thì được dán trên tường.",
        english: "Karendā wa kabe ni hatte arimasu."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "もうVてあります",
    vietnamese: "Đã làm sẵn rồi",
    english: "Mou V-te arimasu",
    type: "additional",
    explanation: "Nhấn mạnh kết quả chuẩn bị sẵn.\nRomaji: Mou V-te arimasu",
    examples: [
      {
        japanese: "食器を洗いましたか。もう洗ってあります。",
        vietnamese: "Đã rửa bát đĩa chưa? Rửa sẵn rồi.",
        english: "Shokki o araimashita ka. Mou aratte arimasu."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Vておきます",
    vietnamese: "Làm trước, chuẩn bị trước",
    english: "V-te okimasu",
    type: "additional",
    explanation: "Làm gì đó trước vì mục đích sau này.\nRomaji: V-te okimasu",
    examples: [
      {
        japanese: "テストのために、たくさん勉強しておきます。",
        vietnamese: "Tôi sẽ học nhiều trước để chuẩn bị cho bài kiểm tra.",
        english: "Tesuto no tame ni, takusan benkyou shite okimasu."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "そのままVておいてください",
    vietnamese: "Cứ để nguyên trạng thái như vậy",
    english: "Sono mama V-te oite kudasai",
    type: "additional",
    explanation: "Nhờ giữ nguyên tình trạng hiện tại.\nRomaji: Sono mama V-te oite kudasai",
    examples: [
      {
        japanese: "そこに置いておいてください。",
        vietnamese: "Cứ để nó ở đó nhé.",
        english: "Soko ni oite oite kudasai."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Vとく / Vといて = Vておく",
    vietnamese: "Dạng nói tắt của Vておく",
    english: "V-toku / V-toite = V-te oku",
    type: "additional",
    explanation: "Văn nói thân mật.\nRomaji: V-toku / V-toite = V-te oku",
    examples: [
      {
        japanese: "そこに置いといて。",
        vietnamese: "Cứ để ở đó nhé.",
        english: "Soko ni oitoite."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "まだVています / まだVていません",
    vietnamese: "Vẫn đang… / vẫn chưa…",
    english: "Mada V-te imasu / mada V-te imasen",
    type: "additional",
    explanation: "Diễn tả trạng thái còn tiếp diễn hoặc chưa hoàn thành.\nRomaji: Mada V-te imasu / mada V-te imasen",
    examples: [
      {
        japanese: "まだ雨が降っています。まだその本を返していません。",
        vietnamese: "Trời vẫn đang mưa. Tôi vẫn chưa trả cuốn sách đó.",
        english: "Mada ame ga futte imasu. Mada sono hon o kaeshite imasen."
      }
    ],
    category: "5. Nhóm te-form (て形 / te-kei): trạng thái, chuẩn bị, hoàn thành"
  },
  {
    pattern: "Vようと思います",
    vietnamese: "Định làm gì",
    english: "V-you to omoimasu",
    type: "additional",
    explanation: "Ý định tại thời điểm nói hoặc dự định chưa quá lâu.\nRomaji: V-you to omoimasu",
    examples: [
      {
        japanese: "三十歳になったら、自分の家を建てようと思います。",
        vietnamese: "Khi 30 tuổi, tôi định xây nhà riêng.",
        english: "Sanjuu-sai ni nattara, jibun no ie o tateyou to omoimasu."
      }
    ],
    category: "6. Nhóm dự định, kế hoạch và ý chí"
  },
  {
    pattern: "Vようと思っています",
    vietnamese: "Đang định / đã ấp ủ dự định",
    english: "V-you to omotte imasu",
    type: "additional",
    explanation: "Ý định đã có từ trước, thể hiện quyết tâm hơn.\nRomaji: V-you to omotte imasu",
    examples: [
      {
        japanese: "日本へ行って天ぷらを食べようと思っています。",
        vietnamese: "Tôi đang định đi Nhật và ăn tempura.",
        english: "Nihon e itte tenpura o tabeyou to omotte imasu."
      }
    ],
    category: "6. Nhóm dự định, kế hoạch và ý chí"
  },
  {
    pattern: "Vるつもりです",
    vietnamese: "Dự định sẽ làm",
    english: "V-ru tsumori desu",
    type: "additional",
    explanation: "Dự định cá nhân, người nói tự lên kế hoạch.\nRomaji: V-ru tsumori desu",
    examples: [
      {
        japanese: "中国語を勉強するつもりです。",
        vietnamese: "Tôi dự định học tiếng Trung.",
        english: "Chuugokugo o benkyou suru tsumori desu."
      }
    ],
    category: "6. Nhóm dự định, kế hoạch và ý chí"
  },
  {
    pattern: "Vないつもりです",
    vietnamese: "Dự định sẽ không làm",
    english: "V-nai tsumori desu",
    type: "additional",
    explanation: "Phủ định của つもりです.\nRomaji: V-nai tsumori desu",
    examples: [
      {
        japanese: "中国語を勉強しないつもりです。",
        vietnamese: "Tôi dự định sẽ không học tiếng Trung.",
        english: "Chuugokugo o benkyou shinai tsumori desu."
      }
    ],
    category: "6. Nhóm dự định, kế hoạch và ý chí"
  },
  {
    pattern: "Vる / Nの + 予定です",
    vietnamese: "Có kế hoạch làm gì",
    english: "V-ru / N no + yotei desu",
    type: "additional",
    explanation: "Kế hoạch đã sắp xếp, thường do tổ chức hoặc nhiều người quyết định.\nRomaji: V-ru / N no + yotei desu",
    examples: [
      {
        japanese: "東京へ出張する予定です。",
        vietnamese: "Tôi có kế hoạch đi công tác Tokyo.",
        english: "Toukyou e shutchou suru yotei desu."
      }
    ],
    category: "6. Nhóm dự định, kế hoạch và ý chí"
  },
  {
    pattern: "でしょう",
    vietnamese: "Chắc là, có lẽ, hẳn là",
    english: "Deshou",
    type: "additional",
    explanation: "Dự đoán tương đối chắc.\nRomaji: Deshou",
    examples: [
      {
        japanese: "明日、雨が降るでしょう。",
        vietnamese: "Ngày mai chắc trời sẽ mưa.",
        english: "Ashita, ame ga furu deshou."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "かもしれません",
    vietnamese: "Có lẽ, có khả năng",
    english: "Kamoshiremasen",
    type: "additional",
    explanation: "Mức độ chắc thấp hơn でしょう.\nRomaji: Kamoshiremasen",
    examples: [
      {
        japanese: "明日は雨かもしれません。",
        vietnamese: "Ngày mai có thể mưa.",
        english: "Ashita wa ame kamoshiremasen."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "Vます bỏ ます / Aい bỏ い / Aな + そうです",
    vietnamese: "Trông có vẻ…, sắp…",
    english: "V-masu stem / A-i bỏ i / A-na + sou desu",
    type: "additional",
    explanation: "Dự đoán bằng mắt, dựa vào vẻ ngoài.\nRomaji: V-masu stem / A-i bỏ i / A-na + sou desu",
    examples: [
      {
        japanese: "このケーキはおいしそうです。",
        vietnamese: "Cái bánh này trông ngon.",
        english: "Kono kēki wa oishisou desu."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "V thường / Aい / Aだ / Nだ + そうです",
    vietnamese: "Nghe nói là…",
    english: "Futsuu-kei + sou desu",
    type: "additional",
    explanation: "Truyền đạt thông tin nghe được từ nguồn khác.\nRomaji: Futsuu-kei + sou desu",
    examples: [
      {
        japanese: "天気予報によると、明日雨が降るそうです。",
        vietnamese: "Theo dự báo thời tiết, nghe nói ngày mai trời mưa.",
        english: "Tenki yohou ni yoru to, ashita ame ga furu sou desu."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "V / Aい / Aな / Nの + ようです",
    vietnamese: "Hình như, dường như",
    english: "V / A-i / A-na / N no + you desu",
    type: "additional",
    explanation: "Phán đoán dựa trên thông tin hoặc giác quan.\nRomaji: V / A-i / A-na / N no + you desu",
    examples: [
      {
        japanese: "彼はN1に合格したようです。",
        vietnamese: "Hình như anh ấy đã đỗ N1.",
        english: "Kare wa N ichi ni goukaku shita you desu."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "V thường / Aい / Aな / N + みたいです",
    vietnamese: "Hình như, giống như",
    english: "Futsuu-kei / A-i / A-na / N + mitai desu",
    type: "additional",
    explanation: "Dạng văn nói của ようです.\nRomaji: Futsuu-kei / A-i / A-na / N + mitai desu",
    examples: [
      {
        japanese: "先生は来ないみたいですね。",
        vietnamese: "Hình như thầy/cô không đến nhỉ.",
        english: "Sensei wa konai mitai desu ne."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "V thường / Aい / Aな / Nの + はずです",
    vietnamese: "Chắc chắn là, đáng lẽ là",
    english: "Futsuu-kei / A-i / A-na / N no + hazu desu",
    type: "additional",
    explanation: "Người nói có căn cứ để kết luận.\nRomaji: Futsuu-kei / A-i / A-na / N no + hazu desu",
    examples: [
      {
        japanese: "雪が降ってきましたから、寒いはずです。",
        vietnamese: "Vì tuyết bắt đầu rơi nên chắc chắn là lạnh.",
        english: "Yuki ga futte kimashita kara, samui hazu desu."
      }
    ],
    category: "7. Nhóm dự đoán, nghe nói và phán đoán"
  },
  {
    pattern: "Vたほうがいいです",
    vietnamese: "Nên làm gì",
    english: "V-ta hou ga ii desu",
    type: "additional",
    explanation: "Đưa lời khuyên nên làm.\nRomaji: V-ta hou ga ii desu",
    examples: [
      {
        japanese: "病院へ行ったほうがいいです。",
        vietnamese: "Bạn nên đi bệnh viện.",
        english: "Byouin e itta hou ga ii desu."
      }
    ],
    category: "8. Nhóm lời khuyên, mệnh lệnh và cấm đoán"
  },
  {
    pattern: "Vないほうがいいです",
    vietnamese: "Không nên làm gì",
    english: "V-nai hou ga ii desu",
    type: "additional",
    explanation: "Đưa lời khuyên không nên làm.\nRomaji: V-nai hou ga ii desu",
    examples: [
      {
        japanese: "風が強いですね。運転しないほうがいいです。",
        vietnamese: "Gió mạnh nhỉ. Không nên lái xe.",
        english: "Kaze ga tsuyoi desu ne. Unten shinai hou ga ii desu."
      }
    ],
    category: "8. Nhóm lời khuyên, mệnh lệnh và cấm đoán"
  },
  {
    pattern: "Vる + な",
    vietnamese: "Đừng làm gì",
    english: "V-ru + na",
    type: "additional",
    explanation: "Cấm đoán mạnh, hay gặp trong biển báo hoặc lời ra lệnh.\nRomaji: V-ru + na",
    examples: [
      {
        japanese: "行くな。",
        vietnamese: "Đừng đi.",
        english: "Iku na."
      }
    ],
    category: "8. Nhóm lời khuyên, mệnh lệnh và cấm đoán"
  },
  {
    pattern: "Vます bỏ ます + なさい",
    vietnamese: "Hãy làm…",
    english: "V-masu stem + nasai",
    type: "additional",
    explanation: "Mệnh lệnh nhẹ, bố mẹ/giáo viên nói với người nhỏ hơn.\nRomaji: V-masu stem + nasai",
    examples: [
      {
        japanese: "早く食べなさい。",
        vietnamese: "Ăn nhanh lên.",
        english: "Hayaku tabenasai."
      }
    ],
    category: "8. Nhóm lời khuyên, mệnh lệnh và cấm đoán"
  },
  {
    pattern: "「X」と読みます",
    vietnamese: "Đọc là X",
    english: "‘X’ to yomimasu",
    type: "additional",
    explanation: "Dùng khi nói cách đọc chữ hoặc ký hiệu.\nRomaji: ‘X’ to yomimasu",
    examples: [
      {
        japanese: "この漢字は「やま」と読みます。",
        vietnamese: "Chữ Kanji này đọc là ‘yama’.",
        english: "Kono kanji wa ‘yama’ to yomimasu."
      }
    ],
    category: "9. Nhóm đọc là, viết là, nghĩa là và trích dẫn"
  },
  {
    pattern: "「X」と書いてあります",
    vietnamese: "Có viết là X",
    english: "‘X’ to kaite arimasu",
    type: "additional",
    explanation: "Chỉ chữ được viết sẵn ở đâu đó.\nRomaji: ‘X’ to kaite arimasu",
    examples: [
      {
        japanese: "あそこに「とまれ」と書いてあります。",
        vietnamese: "Ở kia có viết là ‘Dừng lại’.",
        english: "Asoko ni ‘tomare’ to kaite arimasu."
      }
    ],
    category: "9. Nhóm đọc là, viết là, nghĩa là và trích dẫn"
  },
  {
    pattern: "XはYという意味です",
    vietnamese: "X có nghĩa là Y",
    english: "X wa Y to iu imi desu",
    type: "additional",
    explanation: "Giải thích nghĩa của từ/câu.\nRomaji: X wa Y to iu imi desu",
    examples: [
      {
        japanese: "「ありがとう」は「cảm ơn」という意味です。",
        vietnamese: "‘Arigatou’ có nghĩa là ‘cảm ơn’.",
        english: "‘Arigatou’ wa ‘cảm ơn’ to iu imi desu."
      }
    ],
    category: "9. Nhóm đọc là, viết là, nghĩa là và trích dẫn"
  },
  {
    pattern: "と言いました / と言っていました",
    vietnamese: "Đã nói rằng…",
    english: "To iimashita / to itte imashita",
    type: "additional",
    explanation: "Truyền đạt lời nói của người khác.\nRomaji: To iimashita / to itte imashita",
    examples: [
      {
        japanese: "田中さんが10時に本社に来てくれると言っていました。",
        vietnamese: "Anh Tanaka đã nói rằng anh ấy sẽ đến trụ sở lúc 10 giờ.",
        english: "Tanaka-san ga juuji ni honsha ni kite kureru to itte imashita."
      }
    ],
    category: "9. Nhóm đọc là, viết là, nghĩa là và trích dẫn"
  },
  {
    pattern: "Vる / Vた / Nの + とおりに",
    vietnamese: "Theo như…",
    english: "V-ru / V-ta / N no + toori ni",
    type: "additional",
    explanation: "Làm theo lời nói, hướng dẫn, mẫu có sẵn.\nRomaji: V-ru / V-ta / N no + toori ni",
    examples: [
      {
        japanese: "私が今から言うことのとおりに書いてください。",
        vietnamese: "Hãy viết theo những điều tôi sắp nói.",
        english: "Watashi ga ima kara iu koto no toori ni kaite kudasai."
      }
    ],
    category: "10. Nhóm điều kiện, theo như, sau khi và càng… càng…"
  },
  {
    pattern: "Vた / Nの + あとで",
    vietnamese: "Sau khi…",
    english: "V-ta / N no + ato de",
    type: "additional",
    explanation: "Sau khi hoàn thành vế trước thì làm vế sau.\nRomaji: V-ta / N no + ato de",
    examples: [
      {
        japanese: "新しいのを買ったあとで、なくした本が見つかりました。",
        vietnamese: "Sau khi mua cái mới, tôi đã tìm thấy quyển sách bị mất.",
        english: "Atarashii no o katta ato de, nakushita hon ga mitsukarimashita."
      }
    ],
    category: "10. Nhóm điều kiện, theo như, sau khi và càng… càng…"
  },
  {
    pattern: "Vば",
    vietnamese: "Nếu…",
    english: "V-ba",
    type: "additional",
    explanation: "Thể điều kiện; sau ば thường không dùng mệnh lệnh trực tiếp quá mạnh.\nRomaji: V-ba",
    examples: [
      {
        japanese: "ほかの意見がなければ、これで終わりましょう。",
        vietnamese: "Nếu không có ý kiến khác, chúng ta kết thúc ở đây nhé.",
        english: "Hoka no iken ga nakereba, kore de owarimashou."
      }
    ],
    category: "10. Nhóm điều kiện, theo như, sau khi và càng… càng…"
  },
  {
    pattern: "Vる / Aい / Aな / N + なら",
    vietnamese: "Nếu là…, nếu muốn…",
    english: "V-ru / A-i / A-na / N + nara",
    type: "additional",
    explanation: "Đưa lời khuyên dựa trên điều người kia nói.\nRomaji: V-ru / A-i / A-na / N + nara",
    examples: [
      {
        japanese: "スーパーならこの近くにありますよ。",
        vietnamese: "Nếu là siêu thị thì gần đây có đấy.",
        english: "Sūpā nara kono chikaku ni arimasu yo."
      }
    ],
    category: "10. Nhóm điều kiện, theo như, sau khi và càng… càng…"
  },
  {
    pattern: "Vば Vるほど",
    vietnamese: "Càng… càng…",
    english: "V-ba V-ru hodo",
    type: "additional",
    explanation: "Mức độ tăng dần theo hành động/tính chất.\nRomaji: V-ba V-ru hodo",
    examples: [
      {
        japanese: "日本語を勉強すれば、勉強するほど上手になります。",
        vietnamese: "Càng học tiếng Nhật thì càng giỏi lên.",
        english: "Nihongo o benkyou sureba, benkyou suru hodo jouzu ni narimasu."
      }
    ],
    category: "10. Nhóm điều kiện, theo như, sau khi và càng… càng…"
  },
  {
    pattern: "Vる / Vない + ように、B",
    vietnamese: "Để A thì làm B",
    english: "V-ru / V-nai + you ni, B",
    type: "additional",
    explanation: "A là mục tiêu/trạng thái muốn đạt; B là hành động để đạt mục tiêu.\nRomaji: V-ru / V-nai + you ni, B",
    examples: [
      {
        japanese: "新聞が読めるように、漢字を勉強します。",
        vietnamese: "Tôi học Kanji để có thể đọc báo.",
        english: "Shinbun ga yomeru you ni, kanji o benkyou shimasu."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vる / Nの + ために",
    vietnamese: "Để…, vì mục đích…",
    english: "V-ru / N no + tame ni",
    type: "additional",
    explanation: "Dùng với mục đích có chủ ý rõ ràng.\nRomaji: V-ru / N no + tame ni",
    examples: [
      {
        japanese: "大学に入るために、一生懸命勉強します。",
        vietnamese: "Tôi học chăm chỉ để vào đại học.",
        english: "Daigaku ni hairu tame ni, isshoukenmei benkyou shimasu."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vるようになります",
    vietnamese: "Đã trở nên có thể làm gì",
    english: "V-ru you ni narimasu",
    type: "additional",
    explanation: "Nói sự thay đổi khả năng.\nRomaji: V-ru you ni narimasu",
    examples: [
      {
        japanese: "日本語が話せるようになりました。",
        vietnamese: "Tôi đã có thể nói tiếng Nhật.",
        english: "Nihongo ga hanaseru you ni narimashita."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vなくなります",
    vietnamese: "Trở nên không còn / không thể làm gì",
    english: "V-naku narimasu",
    type: "additional",
    explanation: "Nói sự thay đổi theo hướng mất khả năng hoặc thói quen.\nRomaji: V-naku narimasu",
    examples: [
      {
        japanese: "好きな服が着られなくなりました。",
        vietnamese: "Tôi không mặc được bộ đồ yêu thích nữa.",
        english: "Sukina fuku ga kirarenaku narimashita."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vる / Vない + ようにしています",
    vietnamese: "Cố gắng làm / cố gắng không làm",
    english: "V-ru / V-nai + you ni shite imasu",
    type: "additional",
    explanation: "Nhấn mạnh ý thức cố gắng, chưa chắc thành thói quen hoàn toàn.\nRomaji: V-ru / V-nai + you ni shite imasu",
    examples: [
      {
        japanese: "毎日運動するようにしています。",
        vietnamese: "Tôi đang cố gắng vận động mỗi ngày.",
        english: "Mainichi undou suru you ni shite imasu."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vる / Vない + ようにしてください",
    vietnamese: "Hãy cố gắng làm / đừng làm",
    english: "V-ru / V-nai + you ni shite kudasai",
    type: "additional",
    explanation: "Yêu cầu người khác chú ý thực hiện việc gì.\nRomaji: V-ru / V-nai + you ni shite kudasai",
    examples: [
      {
        japanese: "必ず時間を守るようにしてください。",
        vietnamese: "Nhất định hãy giữ đúng giờ.",
        english: "Kanarazu jikan o mamoru you ni shite kudasai."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vるの / N + に",
    vietnamese: "Dùng cho việc…, cần cho việc…, mất thời gian cho việc…",
    english: "V-ru no / N + ni",
    type: "additional",
    explanation: "Đi với 使う, 役に立つ, 必要だ, 時間がかかる.\nRomaji: V-ru no / N + ni",
    examples: [
      {
        japanese: "この道具はパイプを切るのに使います。",
        vietnamese: "Dụng cụ này dùng để cắt ống.",
        english: "Kono dougu wa paipu o kiru no ni tsukaimasu."
      }
    ],
    category: "11. Nhóm mục đích, thay đổi và cố gắng"
  },
  {
    pattern: "Vて / Vなくて / Aくて / Aで / Nで",
    vietnamese: "Vì… nên…",
    english: "V-te / V-nakute / A-kute / A-de / N-de",
    type: "additional",
    explanation: "Vế sau thường là cảm xúc, trạng thái, khả năng hoặc kết quả đã xảy ra.\nRomaji: V-te / V-nakute / A-kute / A-de / N-de",
    examples: [
      {
        japanese: "家族から電話をもらって、安心しました。",
        vietnamese: "Vì nhận được điện thoại từ gia đình nên tôi yên tâm.",
        english: "Kazoku kara denwa o moratte, anshin shimashita."
      }
    ],
    category: "12. Nhóm nguyên nhân, kết quả, đối lập và trường hợp"
  },
  {
    pattern: "V / Aい / Aなな / Nな + ので",
    vietnamese: "Vì… nên…",
    english: "V / A-i / A-na na / N na + node",
    type: "additional",
    explanation: "Nguyên nhân khách quan, mềm hơn から.\nRomaji: V / A-i / A-na na / N na + node",
    examples: [
      {
        japanese: "バスが遅れたので、学校に遅刻しました。",
        vietnamese: "Vì xe buýt muộn nên tôi đến trường muộn.",
        english: "Basu ga okureta node, gakkou ni chikoku shimashita."
      }
    ],
    category: "12. Nhóm nguyên nhân, kết quả, đối lập và trường hợp"
  },
  {
    pattern: "V thường / Aい / Aな / Nな + のに",
    vietnamese: "Thế mà, vậy mà",
    english: "Futsuu-kei / A-i / A-na / N na + noni",
    type: "additional",
    explanation: "Diễn tả sự trái ngược với kỳ vọng.\nRomaji: Futsuu-kei / A-i / A-na / N na + noni",
    examples: [
      {
        japanese: "冬の山は危険なのに、どうして登るんですか。",
        vietnamese: "Núi mùa đông nguy hiểm vậy mà tại sao bạn lại leo?",
        english: "Fuyu no yama wa kiken na noni, doushite noboru n desu ka."
      }
    ],
    category: "12. Nhóm nguyên nhân, kết quả, đối lập và trường hợp"
  },
  {
    pattern: "Vる / Vた / Vない / Aい / Aな / Nの + 場合",
    vietnamese: "Trong trường hợp…",
    english: "V-ru / V-ta / V-nai / A-i / A-na / N no + baai",
    type: "additional",
    explanation: "Dùng để nêu tình huống giả định hoặc quy định.\nRomaji: V-ru / V-ta / V-nai / A-i / A-na / N no + baai",
    examples: [
      {
        japanese: "授業に間に合わない場合は、クラス長に連絡してください。",
        vietnamese: "Trong trường hợp không kịp giờ học, hãy liên lạc với lớp trưởng.",
        english: "Jugyou ni maniawanai baai wa, kurasu-chou ni renraku shite kudasai."
      }
    ],
    category: "12. Nhóm nguyên nhân, kết quả, đối lập và trường hợp"
  },
  {
    pattern: "Vる / Nの + 途中で",
    vietnamese: "Trên đường / giữa lúc đang làm gì",
    english: "V-ru / N no + tochuu de",
    type: "additional",
    explanation: "Nói việc xảy ra giữa chừng.\nRomaji: V-ru / N no + tochuu de",
    examples: [
      {
        japanese: "会議の途中で、急に電話がかかってきました。",
        vietnamese: "Giữa cuộc họp, đột nhiên có điện thoại gọi đến.",
        english: "Kaigi no tochuu de, kyuu ni denwa ga kakatte kimashita."
      }
    ],
    category: "13. Nhóm thời điểm: giữa chừng, sắp làm, đang làm, vừa làm"
  },
  {
    pattern: "Vるところです",
    vietnamese: "Sắp làm",
    english: "V-ru tokoro desu",
    type: "additional",
    explanation: "Ngay trước khi bắt đầu hành động.\nRomaji: V-ru tokoro desu",
    examples: [
      {
        japanese: "これからコピーするところです。",
        vietnamese: "Bây giờ tôi sắp photo.",
        english: "Kore kara kopī suru tokoro desu."
      }
    ],
    category: "13. Nhóm thời điểm: giữa chừng, sắp làm, đang làm, vừa làm"
  },
  {
    pattern: "Vているところです",
    vietnamese: "Đang làm",
    english: "V-te iru tokoro desu",
    type: "additional",
    explanation: "Đúng lúc đang thực hiện hành động.\nRomaji: V-te iru tokoro desu",
    examples: [
      {
        japanese: "今、会場を用意しているところです。",
        vietnamese: "Bây giờ chúng tôi đang chuẩn bị hội trường.",
        english: "Ima, kaijou o youi shite iru tokoro desu."
      }
    ],
    category: "13. Nhóm thời điểm: giữa chừng, sắp làm, đang làm, vừa làm"
  },
  {
    pattern: "Vたところです",
    vietnamese: "Vừa mới làm xong",
    english: "V-ta tokoro desu",
    type: "additional",
    explanation: "Sự việc vừa xảy ra, khoảng cách rất ngắn với thời điểm nói.\nRomaji: V-ta tokoro desu",
    examples: [
      {
        japanese: "たった今、バスが来たところです。",
        vietnamese: "Xe buýt vừa mới đến lúc nãy.",
        english: "Tatta ima, basu ga kita tokoro desu."
      }
    ],
    category: "13. Nhóm thời điểm: giữa chừng, sắp làm, đang làm, vừa làm"
  },
  {
    pattern: "Vたばかりです",
    vietnamese: "Vừa mới làm",
    english: "V-ta bakari desu",
    type: "additional",
    explanation: "‘Vừa’ theo cảm nhận chủ quan của người nói.\nRomaji: V-ta bakari desu",
    examples: [
      {
        japanese: "さっき昼ごはんを食べたばかりです。",
        vietnamese: "Tôi vừa mới ăn trưa lúc nãy.",
        english: "Sakki hirugohan o tabeta bakari desu."
      }
    ],
    category: "13. Nhóm thời điểm: giữa chừng, sắp làm, đang làm, vừa làm"
  },
  {
    pattern: "Nghi vấn từ + か",
    vietnamese: "Không biết / có biết ai, cái gì, ở đâu, khi nào…",
    english: "Gimonshi + ka",
    type: "additional",
    explanation: "Biến câu hỏi thành một phần trong câu lớn.\nRomaji: Gimonshi + ka",
    examples: [
      {
        japanese: "先生が何を話しているか、わかりません。",
        vietnamese: "Tôi không biết thầy/cô đang nói gì.",
        english: "Sensei ga nani o hanashite iru ka, wakarimasen."
      }
    ],
    category: "14. Nhóm câu hỏi nhúng"
  },
  {
    pattern: "〜かどうか",
    vietnamese: "Có… hay không",
    english: "Ka dou ka",
    type: "additional",
    explanation: "Không có từ nghi vấn, chỉ hỏi đúng/sai hoặc có/không.\nRomaji: Ka dou ka",
    examples: [
      {
        japanese: "行けるかどうか、まだわかりません。",
        vietnamese: "Tôi vẫn chưa biết có đi được hay không.",
        english: "Ikeru ka dou ka, mada wakarimasen."
      }
    ],
    category: "14. Nhóm câu hỏi nhúng"
  },
  {
    pattern: "Nhóm 1: âm cuối hàng う → hàng あ + れる",
    vietnamese: "Chia bị động nhóm 1",
    english: "Gurūpu ichi: u-dan → a-dan + reru",
    type: "additional",
    explanation: "Dùng khi bị/được ai đó làm gì.\nRomaji: Gurūpu ichi: u-dan → a-dan + reru",
    examples: [
      {
        japanese: "書く → 書かれる。",
        vietnamese: "Viết → bị/được viết.",
        english: "Kaku → kakareru."
      }
    ],
    category: "15. Nhóm bị động (受身形 / ukemi-kei)"
  },
  {
    pattern: "Nhóm 2: bỏ る + られる",
    vietnamese: "Chia bị động nhóm 2",
    english: "Gurūpu ni: ru o toru + rareru",
    type: "additional",
    explanation: "Áp dụng cho động từ nhóm 2.\nRomaji: Gurūpu ni: ru o toru + rareru",
    examples: [
      {
        japanese: "食べる → 食べられる。",
        vietnamese: "Ăn → bị/được ăn.",
        english: "Taberu → taberareru."
      }
    ],
    category: "15. Nhóm bị động (受身形 / ukemi-kei)"
  },
  {
    pattern: "する → される / 来る → 来られる",
    vietnamese: "Chia bị động nhóm 3",
    english: "Suru → sareru / kuru → korareru",
    type: "additional",
    explanation: "Động từ bất quy tắc.\nRomaji: Suru → sareru / kuru → korareru",
    examples: [
      {
        japanese: "この仕事は山田さんにされました。",
        vietnamese: "Việc này đã được anh Yamada làm.",
        english: "Kono shigoto wa Yamada-san ni saremashita."
      }
    ],
    category: "15. Nhóm bị động (受身形 / ukemi-kei)"
  },
  {
    pattern: "AはBにV bị động",
    vietnamese: "A bị / được B làm gì",
    english: "A wa B ni ukemi-kei",
    type: "additional",
    explanation: "B là người thực hiện hành động.\nRomaji: A wa B ni ukemi-kei",
    examples: [
      {
        japanese: "私は課長に褒められました。",
        vietnamese: "Tôi được trưởng phòng khen.",
        english: "Watashi wa kachou ni homeraremashita."
      }
    ],
    category: "15. Nhóm bị động (受身形 / ukemi-kei)"
  },
  {
    pattern: "Aは / が + V bị động",
    vietnamese: "A được / bị làm",
    english: "A wa / ga + ukemi-kei",
    type: "additional",
    explanation: "Không nhấn mạnh người thực hiện.\nRomaji: A wa / ga + ukemi-kei",
    examples: [
      {
        japanese: "大阪で展覧会が開かれます。",
        vietnamese: "Triển lãm được tổ chức ở Osaka.",
        english: "Oosaka de tenrankai ga hirakaremasu."
      }
    ],
    category: "15. Nhóm bị động (受身形 / ukemi-kei)"
  },
  {
    pattern: "Aは人によってV bị động",
    vietnamese: "A được phát minh / chế tạo / viết bởi ai",
    english: "A wa hito ni yotte ukemi-kei",
    type: "additional",
    explanation: "Dùng cho phát minh, tác phẩm, công trình.\nRomaji: A wa hito ni yotte ukemi-kei",
    examples: [
      {
        japanese: "電話はグラハム・ベルによって発明されました。",
        vietnamese: "Điện thoại được phát minh bởi Graham Bell.",
        english: "Denwa wa Gurahamu Beru ni yotte hatsumei saremashita."
      }
    ],
    category: "15. Nhóm bị động (受身形 / ukemi-kei)"
  },
  {
    pattern: "Nhóm 1: âm cuối hàng う → hàng あ + せる",
    vietnamese: "Chia sai khiến nhóm 1",
    english: "Gurūpu ichi: u-dan → a-dan + seru",
    type: "additional",
    explanation: "Bắt/cho phép ai làm gì.\nRomaji: Gurūpu ichi: u-dan → a-dan + seru",
    examples: [
      {
        japanese: "話す → 話させる。",
        vietnamese: "Nói → bắt/cho nói.",
        english: "Hanasu → hanasaseru."
      }
    ],
    category: "16. Nhóm sai khiến (使役形 / shieki-kei)"
  },
  {
    pattern: "Nhóm 2: bỏ る + させる",
    vietnamese: "Chia sai khiến nhóm 2",
    english: "Gurūpu ni: ru o toru + saseru",
    type: "additional",
    explanation: "Áp dụng cho động từ nhóm 2.\nRomaji: Gurūpu ni: ru o toru + saseru",
    examples: [
      {
        japanese: "食べる → 食べさせる。",
        vietnamese: "Ăn → bắt/cho ăn.",
        english: "Taberu → tabesaseru."
      }
    ],
    category: "16. Nhóm sai khiến (使役形 / shieki-kei)"
  },
  {
    pattern: "する → させる / 来る → 来させる",
    vietnamese: "Chia sai khiến nhóm 3",
    english: "Suru → saseru / kuru → kosaseru",
    type: "additional",
    explanation: "Động từ bất quy tắc.\nRomaji: Suru → saseru / kuru → kosaseru",
    examples: [
      {
        japanese: "勉強する → 勉強させる。",
        vietnamese: "Học → bắt/cho học.",
        english: "Benkyou suru → benkyou saseru."
      }
    ],
    category: "16. Nhóm sai khiến (使役形 / shieki-kei)"
  },
  {
    pattern: "AはBにNをVさせる",
    vietnamese: "A bắt / cho B làm N",
    english: "A wa B ni N o V-saseru",
    type: "additional",
    explanation: "Dùng với tha động từ.\nRomaji: A wa B ni N o V-saseru",
    examples: [
      {
        japanese: "先生は学生に自由に言わせました。",
        vietnamese: "Giáo viên đã để học sinh tự do nói.",
        english: "Sensei wa gakusei ni jiyuu ni iwasemashita."
      }
    ],
    category: "16. Nhóm sai khiến (使役形 / shieki-kei)"
  },
  {
    pattern: "AはBをVさせる",
    vietnamese: "A bắt / cho B làm hành động tự động từ",
    english: "A wa B o V-saseru",
    type: "additional",
    explanation: "Dùng với tự động từ.\nRomaji: A wa B o V-saseru",
    examples: [
      {
        japanese: "4時半に学生を帰らせます。",
        vietnamese: "Tôi cho học sinh về lúc 4 giờ rưỡi.",
        english: "Yoji han ni gakusei o kaerasemasu."
      }
    ],
    category: "16. Nhóm sai khiến (使役形 / shieki-kei)"
  },
  {
    pattern: "人にNを差し上げます / あげます / やります",
    vietnamese: "Cho / biếu ai cái gì",
    english: "Hito ni N o sashiagemasu / agemasu / yarimasu",
    type: "additional",
    explanation: "差し上げます lịch sự; あげます trung tính; やります dùng cho người dưới, động vật, cây.\nRomaji: Hito ni N o sashiagemasu / agemasu / yarimasu",
    examples: [
      {
        japanese: "社長にプレゼントを差し上げます。",
        vietnamese: "Tôi biếu giám đốc món quà.",
        english: "Shachou ni purezento o sashiagemasu."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "人から / 人にNをいただきます / もらいます",
    vietnamese: "Nhận từ ai cái gì",
    english: "Hito kara / hito ni N o itadakimasu / moraimasu",
    type: "additional",
    explanation: "いただきます lịch sự hơn もらいます.\nRomaji: Hito kara / hito ni N o itadakimasu / moraimasu",
    examples: [
      {
        japanese: "おばあさんにかわいいセーターをもらいました。",
        vietnamese: "Tôi đã nhận được chiếc áo len dễ thương từ bà.",
        english: "Obaasan ni kawaii sētā o moraimashita."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "人が私にNをくださいます / くれます",
    vietnamese: "Ai đó cho mình cái gì",
    english: "Hito ga watashi ni N o kudasaimasu / kuremasu",
    type: "additional",
    explanation: "くださいます lịch sự hơn くれます.\nRomaji: Hito ga watashi ni N o kudasaimasu / kuremasu",
    examples: [
      {
        japanese: "彼氏がバラの花をくれました。",
        vietnamese: "Bạn trai đã tặng tôi hoa hồng.",
        english: "Kareshi ga bara no hana o kuremashita."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "人にVてあげます",
    vietnamese: "Làm gì cho ai",
    english: "Hito ni V-te agemasu",
    type: "additional",
    explanation: "Người nói làm việc gì cho người khác.\nRomaji: Hito ni V-te agemasu",
    examples: [
      {
        japanese: "友達に宿題を教えてあげました。",
        vietnamese: "Tôi đã chỉ bài tập cho bạn.",
        english: "Tomodachi ni shukudai o oshiete agemashita."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "人にVてもらいます",
    vietnamese: "Được / nhờ ai làm gì cho mình",
    english: "Hito ni V-te moraimasu",
    type: "additional",
    explanation: "Mình nhận lợi ích từ hành động của người khác.\nRomaji: Hito ni V-te moraimasu",
    examples: [
      {
        japanese: "友達に写真を撮ってもらいました。",
        vietnamese: "Tôi nhờ bạn chụp ảnh cho.",
        english: "Tomodachi ni shashin o totte moraimashita."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "人がVてくれます",
    vietnamese: "Ai đó làm gì cho tôi",
    english: "Hito ga V-te kuremasu",
    type: "additional",
    explanation: "Người khác làm việc có lợi cho mình.\nRomaji: Hito ga V-te kuremasu",
    examples: [
      {
        japanese: "先生が説明してくれました。",
        vietnamese: "Thầy/cô đã giải thích cho tôi.",
        english: "Sensei ga setsumei shite kuremashita."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "N1にN2をV",
    vietnamese: "Làm V cho mục đích N1",
    english: "N ichi ni N ni o V",
    type: "additional",
    explanation: "に chỉ mục đích sử dụng.\nRomaji: N ichi ni N ni o V",
    examples: [
      {
        japanese: "旅行のお土産に人形を買いました。",
        vietnamese: "Tôi đã mua búp bê làm quà du lịch.",
        english: "Ryokou no omiyage ni ningyou o kaimashita."
      }
    ],
    category: "17. Nhóm cho - nhận"
  },
  {
    pattern: "お + Vます bỏ ます + します",
    vietnamese: "Khiêm nhường ngữ cho động từ thường",
    english: "O + V-masu stem + shimasu",
    type: "additional",
    explanation: "Nói về hành động của mình để hạ mình xuống.\nRomaji: O + V-masu stem + shimasu",
    examples: [
      {
        japanese: "私からお伝えします。",
        vietnamese: "Tôi sẽ truyền đạt lại.",
        english: "Watashi kara otsutae shimasu."
      }
    ],
    category: "18. Nhóm kính ngữ và khiêm nhường ngữ"
  },
  {
    pattern: "ご + danh từ Hán + いたします",
    vietnamese: "Khiêm nhường ngữ với động từ nhóm 3 gốc Hán",
    english: "Go + kango noun + itashimasu",
    type: "additional",
    explanation: "Dùng trong công việc, dịch vụ khách hàng.\nRomaji: Go + kango noun + itashimasu",
    examples: [
      {
        japanese: "ご案内いたします。",
        vietnamese: "Tôi xin được hướng dẫn.",
        english: "Go-annai itashimasu."
      }
    ],
    category: "18. Nhóm kính ngữ và khiêm nhường ngữ"
  },
  {
    pattern: "お + Vます bỏ ます + になります",
    vietnamese: "Tôn kính ngữ",
    english: "O + V-masu stem + ni narimasu",
    type: "additional",
    explanation: "Nói về hành động của người trên/khách hàng.\nRomaji: O + V-masu stem + ni narimasu",
    examples: [
      {
        japanese: "もうお読みになりましたか。",
        vietnamese: "Ngài đã đọc chưa ạ?",
        english: "Mou oyomi ni narimashita ka."
      }
    ],
    category: "18. Nhóm kính ngữ và khiêm nhường ngữ"
  },
  {
    pattern: "お / ご + Vください",
    vietnamese: "Xin hãy…",
    english: "O / go + V kudasai",
    type: "additional",
    explanation: "Cách nói lịch sự hơn Vてください.\nRomaji: O / go + V kudasai",
    examples: [
      {
        japanese: "ご確認ください。",
        vietnamese: "Xin hãy xác nhận.",
        english: "Go-kakunin kudasai."
      }
    ],
    category: "18. Nhóm kính ngữ và khiêm nhường ngữ"
  },
  {
    pattern: "お / ご + Vいただけませんか",
    vietnamese: "Anh/chị có thể… giúp tôi không?",
    english: "O / go + V itadakemasen ka",
    type: "additional",
    explanation: "Cách nhờ vả rất lịch sự.\nRomaji: O / go + V itadakemasen ka",
    examples: [
      {
        japanese: "ご説明いただけませんか。",
        vietnamese: "Anh/chị có thể giải thích giúp tôi được không?",
        english: "Go-setsumei itadakemasen ka."
      }
    ],
    category: "18. Nhóm kính ngữ và khiêm nhường ngữ"
  },
  {
    pattern: "Vてみます",
    vietnamese: "Thử làm",
    english: "V-te mimasu",
    type: "additional",
    explanation: "Làm thử để biết kết quả.\nRomaji: V-te mimasu",
    examples: [
      {
        japanese: "新しい靴を履いてみます。",
        vietnamese: "Tôi sẽ thử đi đôi giày mới.",
        english: "Atarashii kutsu o haite mimasu."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "Vてきます",
    vietnamese: "Đi làm gì rồi quay lại / trở nên…",
    english: "V-te kimasu",
    type: "additional",
    explanation: "Có thể chỉ hành động đi rồi quay lại hoặc sự thay đổi dần.\nRomaji: V-te kimasu",
    examples: [
      {
        japanese: "電話をかけてきます。",
        vietnamese: "Tôi đi gọi điện rồi quay lại.",
        english: "Denwa o kakete kimasu."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "音 / 匂い / 味がします",
    vietnamese: "Có tiếng / có mùi / có vị",
    english: "Oto / nioi / aji ga shimasu",
    type: "additional",
    explanation: "Diễn tả cảm giác nghe, ngửi, nếm.\nRomaji: Oto / nioi / aji ga shimasu",
    examples: [
      {
        japanese: "子供の声がします。",
        vietnamese: "Có tiếng trẻ con.",
        english: "Kodomo no koe ga shimasu."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "Vます bỏ ます / Aい bỏ い / Aな + すぎます",
    vietnamese: "Quá…",
    english: "V-masu stem / A-i bỏ i / A-na + sugimasu",
    type: "additional",
    explanation: "Diễn tả mức độ vượt quá bình thường.\nRomaji: V-masu stem / A-i bỏ i / A-na + sugimasu",
    examples: [
      {
        japanese: "昨日お酒を飲みすぎました。",
        vietnamese: "Hôm qua tôi uống quá nhiều rượu.",
        english: "Kinou osake o nomisugimashita."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "Aい → Aく + V / Aな → Aに + V",
    vietnamese: "Tính từ bổ nghĩa cho động từ",
    english: "A-i → A-ku + V / A-na → A-ni + V",
    type: "additional",
    explanation: "Biến tính từ thành trạng từ.\nRomaji: A-i → A-ku + V / A-na → A-ni + V",
    examples: [
      {
        japanese: "音が小さいですから、大きくしてください。",
        vietnamese: "Vì âm thanh nhỏ nên hãy làm to lên.",
        english: "Oto ga chiisai desu kara, ookiku shite kudasai."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "Nにします",
    vietnamese: "Chọn / quyết định là N",
    english: "N ni shimasu",
    type: "additional",
    explanation: "Dùng khi quyết định món ăn, lựa chọn, kế hoạch.\nRomaji: N ni shimasu",
    examples: [
      {
        japanese: "晩ごはんは和食にしましょう。",
        vietnamese: "Bữa tối chọn món Nhật nhé.",
        english: "Bangohan wa washoku ni shimashou."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "Lượng từ + は",
    vietnamese: "Ít nhất là…",
    english: "Suuryou-shi + wa",
    type: "additional",
    explanation: "Nhấn mạnh mức tối thiểu.\nRomaji: Suuryou-shi + wa",
    examples: [
      {
        japanese: "パーティーをするのに10人は必要です。",
        vietnamese: "Để tổ chức tiệc thì cần ít nhất 10 người.",
        english: "Pātī o suru no ni juunin wa hitsuyou desu."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  },
  {
    pattern: "Lượng từ + も",
    vietnamese: "Tận / những…",
    english: "Suuryou-shi + mo",
    type: "additional",
    explanation: "Nhấn mạnh số lượng nhiều hơn mong đợi.\nRomaji: Suuryou-shi + mo",
    examples: [
      {
        japanese: "学校まで行くのに2時間もかかります。",
        vietnamese: "Đi đến trường mất tận 2 tiếng.",
        english: "Gakkou made iku no ni nijikan mo kakarimasu."
      }
    ],
    category: "19. Nhóm khác rất hay gặp ở N4"
  }
];
