/**
 * Code generation — turns a validated `ExamPaper[]` into the typed data module
 * `src/lib/data/exams/papers.ts` that the UI reads (via `exams/index.ts`).
 *
 * The output is machine-owned: a banner marks it DO-NOT-EDIT and the data is
 * emitted as JSON (valid TS object-literal syntax) sorted N5→N1 for stable
 * diffs. Only `ExamPaper` fields are serialized (no fixture-only keys), so the
 * file type-checks against `ExamPaper[]` under strict TypeScript.
 *
 * @typedef {import('../../src/lib/types/exam').ExamPaper} ExamPaper
 * @typedef {import('../../src/lib/types/exam').JlptLevel} JlptLevel
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
/** Destination data file regenerated by the pipeline. */
export const PAPERS_FILE = resolve(HERE, '..', '..', 'src', 'lib', 'data', 'exams', 'papers.ts');

/** @type {JlptLevel[]} */
const LEVEL_ORDER = ['N5', 'N4', 'N3', 'N2', 'N1'];

/**
 * Stable sort: N5→N1, then by paper id (lexicographic).
 * @param {ExamPaper[]} papers
 * @returns {ExamPaper[]}
 */
export function sortPapers(papers) {
  return [...papers].sort((a, b) => {
    const la = LEVEL_ORDER.indexOf(a.level);
    const lb = LEVEL_ORDER.indexOf(b.level);
    if (la !== lb) return la - lb;
    return a.id.localeCompare(b.id);
  });
}

/** Marker the rendered file uses to introduce the data array. */
const PAPERS_MARKER = 'export const papers: ExamPaper[] = ';

/**
 * Read back the papers currently committed in `papers.ts`. Used by the
 * orchestrator's MERGE mode so a single-source run can add/replace only the
 * papers it owns (keyed by id) without dropping papers contributed by other
 * sources. The generated file is machine-owned with exactly the shape emitted by
 * {@link renderPapersFile}, so the data array is plain JSON.
 *
 * @param {string} [file]
 * @returns {ExamPaper[]}  `[]` when the file does not exist yet.
 */
export function readExistingPapers(file = PAPERS_FILE) {
  if (!existsSync(file)) return [];
  const src = readFileSync(file, 'utf8');
  const at = src.indexOf(PAPERS_MARKER);
  if (at === -1) {
    throw new Error(`cannot read existing papers: marker not found in ${file} (corrupted machine file?)`);
  }
  let tail = src.slice(at + PAPERS_MARKER.length).trimEnd();
  if (tail.endsWith(';')) tail = tail.slice(0, -1);
  try {
    const parsed = JSON.parse(tail);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    throw new Error(`cannot parse existing papers in ${file}: ${err instanceof Error ? err.message : String(err)}`);
  }
}

/**
 * Merge freshly-produced papers into an existing set, keyed by paper `id`:
 * any existing paper whose id collides with a produced paper is replaced; all
 * other existing papers are kept. Deterministic + idempotent (re-running a
 * source replaces exactly its own ids).
 *
 * @param {ExamPaper[]} existing
 * @param {ExamPaper[]} produced
 * @returns {ExamPaper[]}
 */
export function mergePapers(existing, produced) {
  const producedIds = new Set(produced.map((p) => p.id));
  return existing.filter((p) => !producedIds.has(p.id)).concat(produced);
}

/**
 * Render the full `papers.ts` source for a set of papers.
 * @param {ExamPaper[]} papers
 * @returns {string}
 */
export function renderPapersFile(papers) {
  const sorted = sortPapers(papers);
  const json = JSON.stringify(sorted, null, 2);
  return (
    `/**\n` +
    ` * Exam paper data (static, offline-first).\n` +
    ` *\n` +
    ` * AUTO-GENERATED by \`scripts/fetch-exams/\` — DO NOT EDIT BY HAND.\n` +
    ` * Re-generate with: \`npm run fetch-exams\` (default --source=fixture).\n` +
    ` * The UI must import only from \`./index.ts\`, never this file directly.\n` +
    ` */\n\n` +
    `import type { ExamPaper } from '$lib/types/exam';\n\n` +
    `${PAPERS_MARKER}${json};\n`
  );
}

/**
 * Write the rendered file to disk.
 * @param {ExamPaper[]} papers
 * @param {string} [file]
 * @returns {string}  The path written.
 */
export function writePapersFile(papers, file = PAPERS_FILE) {
  writeFileSync(file, renderPapersFile(papers), 'utf8');
  return file;
}
